models:
  - model_name: DQN
    parameters:
      width: 10
      height: 20
      block_size: 30
      batch_size: 512
      lr: 0.001
      gamma: 0.99
      initial_epsilon: 1
      final_epsilon: 0.001
      num_decay_epochs: 2000
      num_epochs: 3000
      save_interval: 1000
      replay_memory_size: 30000
      max_score: 30000
      target_update: 4
      log_path: "DQN/logs"
      saved_path: "DQN/trained_models"
      device: "cpu"
  - model_name: DDQN
    parameters:
      width: 10
      height: 20
      block_size: 30
      batch_size: 512
      lr: 0.001
      gamma: 0.99
      initial_epsilon: 1
      final_epsilon: 0.001
      num_decay_epochs: 2000
      num_epochs: 3000
      save_interval: 1000
      replay_memory_size: 30000
      max_score: 30000
      target_update: 4
      log_path: "DDQN/logs"
      saved_path: "DDQN/trained_models"
      device: "cpu"
  - model_name: NoisyDQN
    parameters:
      width: 10
      height: 20
      block_size: 30
      batch_size: 512
      lr: 0.001
      gamma: 0.99
      initial_epsilon: 1
      final_epsilon: 0.001
      num_decay_epochs: 2000
      num_epochs: 3000
      save_interval: 1000
      replay_memory_size: 30000
      max_score: 30000
      target_update: 4
      log_path: "NoisyDQN/logs"
      saved_path: "NoisyDQN/trained_models"
      device: "cpu"
  - model_name: SAC
    parameters:
      width: 10
      height: 20
      block_size: 30
      batch_size: 512
      hidden_size: 256
      lr: 0.000005
      alpha: 0.2
      gamma: 0.99
      tau: 0.01
      initial_epsilon: 1
      final_epsilon: 0.001
      num_decay_epochs: 2000
      num_epochs: 10000
      save_interval: 1000
      replay_memory_size: 30000
      max_score: 30000
      log_path: "SAC/logs"
      saved_path: "SAC/trained_models"

  # - model_name: PPO
  #   parameters:
  #     learning_rate: 0.00025
  #     gamma: 0.95
  #     gae_lambda: 0.95
  #     entropy_coefficient: 0.01
  #     value_loss_coefficient: 0.5
  #     epsilon_clip: 0.2
  #     num_epochs: 10
  #     batch_size: 64
  - model_name: PG
    parameters:
      width: 10
      height: 20
      block_size: 30
      batch_size: 512
      hidden_size: 256
      lr: 0.0001
      alpha: 0.2
      gamma: 0.99
      num_decay_epochs: 10000000
      num_epochs: 10000000
      save_interval: 100
      log_interval: 10
      max_score: 30000
      log_path: "PG/logs"
      saved_path: "PG/trained_models"

  - model_name: PPO
    parameters:
      width: 10
      height: 20
      block_size: 30
      batch_size: 512
      hidden_size: 256
      lr: 0.0001
      alpha: 0.2
      gamma: 0.99
      num_decay_epochs: 100000
      num_epochs: 1000000
      save_interval: 1000
      log_interval: 100
      max_score: 30000
      num_trials: 25
      log_path: "PPO/logs"
      saved_path: "PPO/trained_models"